In [1]:
import numpy as np 
import pandas as pd 
import seaborn as sns 
from matplotlib import pyplot as plt
import warnings
warnings.filterwarnings("ignore")

### K-Nearest Neighbors 
--- 
How KNN works: 
 - choose the value of k
 - at train phase dont do anything, just store X and y
 - At prediction phase:
    1. Find the distance from prediction point to all the training points.
    2. Sort the distance in ascending order.
    3. Take the K numbers of nearest training samples.
    4. Now for classification use `Voting` and for regression use `Mean`.  

In [26]:
class KNN_Classifier: 
    def __init__(self , n_neighbors = 3 , distance_metrics = "Euclidean"): 
        self.n_neighbors = n_neighbors 
        self.distance_metrics = distance_metrics 
    
    def fit(self , X , y): 
        # Just store the train values
        self.X_train = X 
        self.y_train = y

    # this will take the full X_test and do the prediction 
    def predict(self , X_test): 
        y_pred = np.array([self._pred(x) for x in X_test])
        return y_pred
        
    # take a single row/sample from the total predicitions   
    def _pred(self , x): 
        # we have a single row x 
        n_samples , _ = self.X_train.shape

        distances = []
        
        # now traverse all the rows in X_train 
        for index in range(n_samples): 
            # extract the current index values
            row = self.X_train[index , : ] 
            # based on the given distance metrics find the distance 
            if self.distance_metrics == 'Euclidean': 
                distance = self._euclidean(x , row)
            else:
                distance = self._manhattan(x , row) 

            # store the distance 
            distances.append(distance)
            
        # sort the disinstances 
        distances = np.array(distances)
        sorted_indices = np.argsort(distances)
        
        # now find the k nearest(smallest distances)
        k_nearest = sorted_indices[ : self.n_neighbors]

        # now find the most common label
        k_nearest_labels = self.y_train[k_nearest]

        # now count the frequency 
        from collections import Counter
        count = Counter(k_nearest_labels)
        most_common_label = count.most_common(1)[0][0]
        return most_common_label
        
    def _euclidean(self , p1 , p2): # Find the euclidean distance between 2 points
        return np.sqrt(np.sum((p1 - p2) ** 2)) 

    def _manhattan(self , p1 , p2): # Find the _manhattan distance between 2 points
        return np.sum(np.abs(p1 - p2)) 

In [37]:
# KNN Regressor 
class KNN_Regressor: 
    def __init__(self , n_neighbors = 3 , distance_metrics = "Euclidean"): 
        self.n_neighbors = n_neighbors 
        self.distance_metrics = distance_metrics 
    
    def fit(self , X , y): 
        # Just store the train values
        self.X_train = X 
        self.y_train = y

    # this will take the full X_test and do the prediction 
    def predict(self , X_test): 
        y_pred = np.array([self._pred(x) for x in X_test])
        return y_pred
        
    # take a single row/sample from the total predicitions   
    def _pred(self , x): 
        # we have a single row x 
        n_samples , _ = self.X_train.shape

        distances = []
        
        # now traverse all the rows in X_train 
        for index in range(n_samples): 
            # extract the current index values
            row = self.X_train[index , : ] 
            # based on the given distance metrics find the distance 
            if self.distance_metrics == 'Euclidean': 
                distance = self._euclidean(x , row)
            else:
                distance = self._manhattan(x , row) 

            # store the distance 
            distances.append(distance)
            
        # sort the disinstances 
        distances = np.array(distances)
        sorted_indices = np.argsort(distances)
        
        # now find the k nearest(smallest distances)
        k_nearest = sorted_indices[ : self.n_neighbors]

        # now find the most common label
        k_nearest_labels = self.y_train[k_nearest]

        # label will be the mean of k_nearest_labels 
        return np.mean(k_nearest_labels)
        
    def _euclidean(self , p1 , p2): # Find the euclidean distance between 2 points
        return np.sqrt(np.sum((p1 - p2) ** 2)) 

    def _manhattan(self , p1 , p2): # Find the _manhattan distance between 2 points
        return np.sum(np.abs(p1 - p2)) 

In [4]:
x1 = np.array([1,2,3])
x2 = np.array([2,1,3])

e_dis = np.sqrt(np.sum((x1 - x2) ** 2))

e_dis

np.float64(1.4142135623730951)

In [5]:
m_dis = np.sum(np.abs(x1 - x2))
m_dis

np.int64(2)

In [6]:
a = np.array([
    [1,2,3], 
    [4,5,6], 
    [7,8,9]
])

In [7]:
row2 = a[1 , : ]
row2

array([4, 5, 6])

In [8]:
distances = np.array([8,5,9,1,1,4,3])
sorted_index = np.argsort(distances)
sorted_index

array([3, 4, 6, 5, 1, 0, 2])

In [13]:
all_dis = distances[sorted_index]
k_near = all_dis[ : 3]

In [15]:
y = np.array([0,1,1,0,1])
labels = y[k_near]

In [20]:
labels

array([1, 1, 0])

In [21]:
from collections import Counter

count = Counter(labels)
count

Counter({np.int64(1): 2, np.int64(0): 1})

In [25]:
target = count.most_common(1)[0][0]
target

np.int64(1)

### Testing

In [27]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [28]:
iris = load_iris() 
X , y = iris.data , iris.target

In [31]:
X = StandardScaler().fit_transform(X)

In [32]:
X_train , X_test , y_train , y_test = train_test_split(X , y , test_size = 0.2 , random_state = 42)

In [35]:
# Load our KNN model 
our_model = KNN_Classifier(n_neighbors = 3)
our_model.fit(X_train , y_train)
y_pred = our_model.predict(X_test)

In [36]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test , y_pred)

1.0

In [38]:
from sklearn.datasets import load_diabetes
from sklearn.metrics import mean_squared_error , r2_score

In [39]:
# Load regression dataset
X, y = load_diabetes(return_X_y = True)
X = StandardScaler().fit_transform(X)
X_train , X_test , y_train , y_test = train_test_split(X , y , test_size = 0.2 , random_state = 42)

In [40]:
knn_reg = KNN_Regressor(n_neighbors=5)
knn_reg.fit(X_train, y_train)
y_pred = knn_reg.predict(X_test)

In [41]:
print("R2 score:", r2_score(y_test, y_pred))
print("MSE:", mean_squared_error(y_test, y_pred))

R2 score: 0.43016439526042805
MSE: 3019.075505617978


In [42]:
from sklearn.neighbors import KNeighborsRegressor

sk_knn_reg = KNeighborsRegressor(n_neighbors = 5 , metric = 'euclidean') 
sk_knn_reg.fit(X_train , y_train)

,n_neighbors,5
,weights,'uniform'
,algorithm,'auto'
,leaf_size,30
,p,2
,metric,'euclidean'
,metric_params,None
,n_jobs,None


In [43]:
y_pred_sk = sk_knn_reg.predict(X_test)

In [44]:
print("R2 score:", r2_score(y_test, y_pred_sk))
print("MSE:", mean_squared_error(y_test, y_pred_sk))

R2 score: 0.43016439526042805
MSE: 3019.075505617978
